### ISSUE TITLE
how to connect cluster

### ISSUE THREAD

**Issue by pool611** [yellowgg2/easy-redis#1]
how to connect cluster and what is the format of IP, Port and Password?
I could't see it in usage.
look for your help :)
thanks

**Comment by yellowgg2** [comment]
Unfortunately, you won't be able to use cluster with this extension T_T.

I didn't implement the feature, but I will someday...maybe...

You can compose of ip, port and password in one url format:

The URL of the Redis server. Format: [redis:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]] 

For instance, **redis://user:password@192.168.11.11:9000**

I hope this help you :)

**Comment by pool611** [comment]
Thank you 👍 
Maybe ioredis is better than redis in npm and it support  Cluster, Sentinel, Pipelining and Lua scripting & Pub/Sub.
파이팅!

**Comment by yellowgg2** [comment]
I should consider to use ioredis instead of redis package. 

Thanks for the advice!
