### ISSUE TITLE
Flush and delete many feature

### ISSUE THREAD

**Issue by tuurbo** [yellowgg2/easy-redis#2]
Thanks for this great extension!

Have you considered adding a "flush all" icon and/or the ability to delete multiple selected items at once?

Thanks again

**Comment by yellowgg2** [comment]
I think I can add "flush all" feature easily.

You will be able to see that feature sooner.

Thank you for the suggestion. 👍

**Comment by yellowgg2** [comment]
@tuurbo I just added "flush all" feature and also facilitated deleting item.

You should be able to update the extension right away.

Enjoy!

**Comment by tuurbo** [comment]
Wow that was fast. Thanks so much!
