### ISSUE TITLE
How to refresh and disconnect?

### ISSUE THREAD

**Issue by sgon00** [yellowgg2/easy-redis#4]
Hi, first, thank you very much for this extension. I have starred it. 

(1) After adding new keys in redis-cli, I don't find a way to refresh the view in REDIS EXPLORER. The only way to do refresh, it's Reload WIndow which takes a long time and many CPU resources. 

(2) I don't find a way to disconnect redis server. So far, I can only disable this extension to disable the redis server connection.

(3)Are you going to support other types? I found out other types didn't work properly. 

Thanks a lot.

**Comment by oji** [comment]
+1

**Comment by spike886** [comment]
+1

**Comment by yellowgg2** [comment]
@sgon00 @oji Sorry for late. I just updated extension.
Added `refresh`, `disconnect` feature.
It doesn't support other types yet but will soon.

Thanks!
