### ISSUE TITLE
Show all databases

### ISSUE THREAD

**Issue by Anvoony** [yellowgg2/easy-redis#5]
Hi,

I'm wondering how I could show all my databases ?
Currently it's only possible to see the db0.

Thanks, the extension is great !

**Comment by yellowgg2** [comment]
@Anvoony Sorry for late. I don't know this is enough for your request.

You can now connect to other db.
Add server as url like:
```conf
# Connect to 127.0.0.1:6380, db 4, using password "authpassword"
redis://:authpassword@127.0.0.1:6380/4
```
